name: Go Build and Release

# on:
#   push:
#     tags:
#       - 'v*'
on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        OS: [linux, windows]
        ARCH: [amd64]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Build
        run: |
          env GOOS=${{ matrix.OS }} GOARCH=${{ matrix.ARCH }} go build -v -o mediarizer2-${{ matrix.OS }}-${{ matrix.ARCH }} ./app

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mediarizer2-${{ matrix.OS }}-${{ matrix.ARCH }}
          path: mediarizer2-${{ matrix.OS }}-${{ matrix.ARCH }}

  release:
    needs: build
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Release ${{ github.run_number }}
            - continuous deployment
          draft: false
          prerelease: false

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Upload Release Asset Linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts
          asset_name: mediarizer2-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts
          asset_name: mediarizer2-windows-amd64
          asset_content_type: application/octet-stream